#/bin/bash

# this scripts:
# 2 - creates nc4 files 
# 3 - launches CEM 
# it uses BellmanVauesOUT.csv or cuts.txt generated by SSV, which have
# to be present in ${INSTANCE}

source include/include.sh

rm -r ${INSTANCE}results_invest
mkdir ${INSTANCE}results_invest

# in case sddp has not converged, use cuts instead of bellmanvaluesout
cp ${INSTANCE}cuts.txt ${INSTANCE}results_invest/
cp ${INSTANCE}BellmanValuesOUT.csv ${INSTANCE}results_invest/

# run formatting script to create netcdf input files for the investment model
echo -e "\n${print_orange}Step 1 - Create netcdf input files to run the CEM: ${no_color}${P4R_ENV} python -W ignore ${PYTHONSCRIPTS}format.py /${CONFIG}settings_format_invest.yml /${CONFIG}settingsCreateInputPlan4res_invest.yml ${DATASET}"
rm -r ${INSTANCE}nc4_invest
source scripts/include/formatCEM.sh

# run investment solver
echo -e "\n${print_orange}Step 2 - run CEM using investment_solver:${no_color}${P4R_ENV} investment_solver -l ${INSTANCE}results_invest/bellmanvalues.csv -o -e -S ${CONFIG}BSPar-Investment.txt -c ${CONFIG} -p ${INSTANCE}nc4_invest/ ${INSTANCE}nc4_invest/InvestmentBlock.nc4"
source scripts/include/cem.sh

# run post treatment script
echo -e "\n${print_orange}Step 3 - launch post treat:${no_color}${P4R_ENV} python -W ignore ${PYTHONSCRIPTS}PostTreatPlan4res.py /${CONFIG}settingsPostTreatPlan4res_invest.yml /${CONFIG}settings_format_invest.yml /${CONFIG}settingsCreateInputPlan4res_invest.yml ${DATASET}"
source scripts/include/postreatCEM.sh
