#/bin/bash

# this scripts:
# 2 - creates nc4 files 
# 3 - launches CEM 
# it uses BellmanVauesOUT.csv or cuts.txt generated by SSV, which have
# to be present in ${INSTANCE}

source include/utils.sh

phasecreate="invest"
phaseformat="invest"
phasepostreat="invest"

rm -r ${INSTANCE}results_invest
mkdir ${INSTANCE}results_invest

# in case sddp has not converged, use cuts instead of bellmanvaluesout
cp ${INSTANCE}cuts.txt ${INSTANCE}results_invest/
cp ${INSTANCE}BellmanValuesOUT.csv ${INSTANCE}results_invest/

# run formatting script to create netcdf input files for the investment model
echo -e "\n${print_orange}Step 1 - Create netcdf input files to run the CEM ${no_color}"
rm -r ${INSTANCE}nc4_invest
source scripts/include/format.sh

# run investment solver
echo -e "\n${print_orange}Step 2 - run CEM"
source scripts/include/cem.sh

# run post treatment script
echo -e "\n${print_orange}Step 3 - launch post treat"
source scripts/include/postreat.sh
