#/bin/bash

# this scripts:
# 1 - creates nc4 files 
# 2 - launches SIM 
# 3 - launches post treatments
# it uses BellmanVauesOUT.csv or cuts.txt generated by SSV, which have
# to be present in ${INSTANCE}

source scripts/include/utils.sh

phasecreate="simul"
phaseformat="simul"
phasepostreat="simul"

rm -r ${INSTANCE}/results_simul
mkdir ${INSTANCE}/results_simul

# in case sddp has not converged, use cuts instead of bellmanvaluesout
cp ${INSTANCE}/cuts.txt ${INSTANCE}/results_simul/
cp ${INSTANCE}/BellmanValuesOUT.csv ${INSTANCE}/results_simul/

# run formatting script to create netcdf input files for the SIM
rm -r ${INSTANCE}/nc4_simul
source scripts/include/format.sh

# run simulations using sddp_solver
#source scripts/include/sim.sh
# alternative: run simulations using investment_solver
source scripts/include/simCEM.sh

# run post treatment script
source scripts/include/postreat.sh