#/bin/bash

# this scripts:
# 1 - creates nc4 files 
# 2 - launches SIM 
# 3 - launches post treatments
# it uses BellmanVauesOUT.csv or cuts.txt generated by SSV, which have
# to be present in ${INSTANCE}

source include/include.sh

rm -r ${INSTANCE}results_simul
mkdir ${INSTANCE}results_simul

# in case sddp has not converged, use cuts instead of bellmanvaluesout
cp ${INSTANCE}cuts.txt ${INSTANCE}results_simul/
cp ${INSTANCE}BellmanValuesOUT.csv ${INSTANCE}results_simul/

# run formatting script to create netcdf input files for the SIM
echo -e "\n${print_orange}Step 1 - Create netcdf input files to run the SIM: ${no_color}${P4R_ENV} python -W ignore ${PYTHONSCRIPTS}format.py /${CONFIG}settings_format_simul.yml /${CONFIG}settingsCreateInputPlan4res_simul.yml ${DATASET}"
rm -r ${INSTANCE}nc4_simul
source scripts/include/formatSIM.sh

# run simulations using sddp_solver
#echo -e "\n${print_orange}Step 2 - run SIM using sddp_solver:${no_color}${P4R_ENV} sddp_solver -l ${INSTANCE}results_simul/bellmanvalues.csv -s -i $scen -S ${CONFIG}sddp_greedy.txt -c ${CONFIG} -p ${INSTANCE}nc4_simul/ ${INSTANCE}nc4_simul/SDDPBlock.nc4"
#source scripts/include/sim.sh
# alternative: run simulations using investment_solver
echo -e "\n${print_orange}Step 2 - run SIM using investment_solver:${no_color}${P4R_ENV} investment_solver -s -l ${INSTANCE}results_simul/bellmanvalues.csv -S ${CONFIG}BSPar_investment.txt -c ${CONFIG} -p ${INSTANCE}nc4_simul/ ${INSTANCE}nc4_simul/InvestmentBlock.nc4"
source scripts/include/simCEM.sh

# run post treatment script
echo -e "\n${print_orange}Step 3 - launch post treat:${no_color}${P4R_ENV} python -W ignore ${PYTHONSCRIPTS}PostTreatPlan4res.py /${CONFIG}settingsPostTreatPlan4res_simul.yml /${CONFIG}settings_format_simul.yml /${CONFIG}settingsCreateInputPlan4res_simul.yml ${DATASET}"
source scripts/include/postreatSIM.sh