# settings for PostTreatPlan4res.py

# optional: dates on which to treat the output
BeginTreatData: '02/07/2030 00:00'
EndTreatData: '30/06/2031 23:00'

# directories
# dir: for reading results of plan4res : 
Resultsdir: 'results_simul_disaggr/' # repository where all results are in subdirectories mydirectory/variant/  or mydirectory/variant-option/

# variables for defining which treatments  will be done
map: yes   # if True: maps will be created ; only possible if geopandas is available
geopandas: yes # False if geopandas is not available; in that case , maps will be skiped
private_map: 'NUTS_RG_60M_2021_4326.geojson'
map_region: 'Europe'
map_country_col: CNTR_CODE
exclude_regions: ['FRY','ES53','FI2','ES70']

# Treatments to be performed
PostTreat:
    Volume: 
        read: yes  # reads volume outputs and create volume files to be used by 'draw' , 'latex' and 'iamc'
        draw: yes  # create graphs
        latex: no  # write latex chapter
        iamc: no  # convert outputs to openentrance format
        Dir: 'Volume/'  # outputs of plan4res for Volumes are in dir/variant-option/Volume/  => files VolumeOUTi.csv
    Flows: 
        read: yes # reads flows outputs and create volume files to be used by 'draw' , 'latex' and 'iamc'
        draw: yes
        latex: no
        iamc: no
        Dir: 'Flows/'
    Power:
        read: yes # reads volume outputs and create volume files to be used by 'draw' , 'latex', 'cmputecost' and 'iamc'
        computecost: yes  # compute variable costs
        draw: yes
        latex: no
        iamc: no
        Dir: 'ActivePower/'
    MarginalCost: 
        read: yes # reads volume outputs and create volume files to be used by 'draw' , 'latex' and 'iamc'
        draw: yes
        latex: no 
        iamc: no
        update: yes  # compute "marginal cost" as the highest cost of started asset
        Dir: 'MarginalCosts/'
        max: 1000
    MarginalCostFlows:
        read: yes # reads volume outputs and create volume files to be used by 'draw' , 'latex' and 'iamc'
        draw: yes
        latex: no
        iamc: no
        Dir: 'MarginalCosts/'
    Demand:
        read: yes # reads volume outputs and create volume files to be used by 'draw' , 'latex' and 'iamc'
        draw: yes
        latex: no
        iamc: no
        Dir: 'Demand/'
    InstalledCapacity:
        draw: yes  # read output files from dir/OUT and creates hraphs in dir/IMG
        latex: no # read output files in dir/OUT and graphs in dir/IMG and create a report in dir/Latex
        iamc: no  # read output files and convert them to open entrance format in dir/IAMC
    SpecificPeriods: # optional - detailed treatments of specifis sub periods on specific scenarios
        read: no    
        latex: no
        iamc: no
        draw: no
        scenarios: [] #subset of scenarios on which to perform detailed analysis on specific periods
        periods:
            #myperiod1:       
                #begin: '02/07/2030 00:00'
                #end: '08/07/2030 23:00'
            # myperiod2:       
                # begin: '2030-12-09T00:00+01:00'
                # end: '2030-12-15T23:00+01:00'

# dimensions of graphics
Graphs:
    Volume: 
        nbcols: 3
        nblines: 6
        SizeCol: 50
        SizeRow: 50
        TitleSize: 50
        LabelSize: 40
    Power:
        #treat: ['Hydro','Geothermal','Biomass','WindPower','Nuclear','PV','Hydrogen','Coal','Gaz','Oil'] # use if only a sublist of technos are in the graphs
        nbcols: 4
        nblines: 5
        SizeCol: 50
        SizeRow: 35
        TitleSize: 50
        LabelSize: 40
        ChloroGraph:
            nbcols: 4
            nblines: 4
            dpi: 50
    MarginalCost: 
        nbcols: 4
        nblines: 6
        SizeCol: 50
        SizeRow: 35
        TitleSize: 50
        LabelSize: 40
    MarginalCostFlows:
        nbcols: 5
        nblines: 10
    Demand:
        nbcols: 4
        nblines: 6
        SizeCol: 50
        SizeRow: 35
        TitleSize: 50
        LabelSize: 40

# name of scenario for the IAMC file
scenario: 'eHighway 2050'
model: 'plan4res v1.0'  # name of the model

# name and title of the latex report
namereport: 'nameofthereport'
titlereport: 'Title of the report'

# if bellman value is to be computed (file BellmanOUT.csv in inputs): yes, else: no
usevu: no
# SSVTimeStep number in BellmanOUT.csv corresponding to plot_end
timestepvusms: 14
# figures are rounded: 1, not rounded: 0
arrondi: 1
# min and max of the marginal cost graphs
marginalcostlimits:
    max: 10000
    min: -10000
pielimit: 0.001

# information per technology:
# color= hex code of the color to use for this technology
# the following should be read from the data
# cO2= cO2 cost per MWh for this technology
# varcost= Variable cost Euro per MWh for this technology
# startcost= Start-Up cost Euro

Technos:
    RoR: 
        color: '#74DBDA'
    'Nuclear ':
        color: '#FFAA00'
    'Coal without CCS ':
        color: '#0D0D0D'
    'Lignite without CCS ':
        color: '#2F3030'
    'Nuclear':
        color: '#FFAA00'
    'Coal without CCS':
        color: '#0D0D0D'
    'Lignite without CCS':
        color: '#2F3030'
    WindOffshore:
        color: '#2BFF00'
    WindOnshore:
        color: '#22CC00'
    PV:
        color: '#FFFF00'
    'Biomass I ':
        color: '#608000'
    'Biomass II ':
        color: '#608000'
    'Gas without CCS ':
        color: '#FF0000'
    'OCGT ':
        color: '#4F0000'
    'Biomass I':
        color: '#608000'
    'Biomass II':
        color: '#608000'
    'Gas without CCS':
        color: '#FF0000'
    'OCGT':
        color: '#4F0000'
    Reservoir :
        color: '#0000FF'
    PSP :
        color: '#3377FF'
    Import:
        color: '#D75BE1'
    SlackUnit:
        color: '#FFFFFF'
    PSP_PUMP:
        color: '#3377FF'

# aggregated technologies (for aggregated graphs)
# for each aggr techno: list of technos and color codes 
technosAggr:
    Hydro:
        technos: ['Reservoir',  'PSP', 'RoR']
        color: blue
        colors: Blues
    Hydro_PUMP:
        technos: ['PSP_PUMP']
        color: blue
        colors: Blues
    WindPower:
        technos: ['WindOffshore', 'WindOnshore']
        color: green
        colors: Greens
    PV:
        technos: ['PV']
        color: yellow
        colors: YlOrRd
    Biomass: 
        technos: ['Biomass I ','Biomass II ','Biomass I','Biomass II']
        color: darkkhaki
        colors: Greens
    Nuclear:
        technos: ['Nuclear ','Nuclear']
        color: orange
        colors: Oranges
    Coal:
        technos: ['Coal without CCS ','Lignite without CCS ','Coal without CCS','Lignite without CCS']
        color: black
        colors: Greys
    Gaz:
        technos: ['Gas without CCS ','OCGT ','Gas without CCS','OCGT']
        color: firebrick
        colors: Reds
    Import:
        technos: ['Import']
        color: saddlebrown
        colors: Greys
    Non Served:
        technos: ['SlackUnit']
        color: blueviolet
        colors: Purples
        
# lists of storage units
# pumping=list of units with pumping capacity
# nopumping=list of units without pumping capacity
pumping: [ 'Pumped Storage', 'Compressed Air','Lithium-Ion']
nopumping: [ 'Reservoir' ]

# specification of deterministic graphics for storages
graphVolumes:
    Reservoir: 
        Name: 'Reservoir' # name of graph
        Technos: ['Reservoir'] # technos included
    PumpedStorage: 
        Name: 'Pumped Storage'
        Technos: ['PSP']

#############################################
#
# optional data to be included only if theres
# is not a settingsCreateInputPlan4res.yml 
# config file, ie if the csv files were
# created by other means than using the
# CreateInputPlan4res.py script
# nor a settings_format_XXX.yml file
# ie if the nc4 files were not created
# using format.py
#
#############################################
# if data are located within the plan4res container, use plan4res path
#USEPLAN4RESROOT: True

# dates information:
# - dayfirst: True if the format is giving the day first (01/07/2050 means first of july)
# - BeginTimeSeries : first day of the datasets
# - EndTimeSeries : last day of the datasets
# - BeginDataset : first day of the instance to create
# - EndDataset: last day of the instance to create
# Calendar:
    # dayfirst: True 
    # BeginDataset: '02/07/2030  00:00:00'
    # TimeStep:  # duration of timesteps 
        # Unit: hours
        # Duration: 1
# # path where the dataset is located (in subdirs nc4*)
# path: '/data/local/InputPlan4res/'
#ParametersFormat: 
#    Scenarios: ['1982','1983'] # list of scenarios to include in the instance (names of scenarios)
